### ISSUE TITLE
Direct support for pub/sub in message store database retrieval functions

### ISSUE THREAD

**Issue by sbellware** [eventide-project/message-store-postgres-database#5]
Pub/Sub based on the correlation stream name's category (ie: inter-service pub/sub) is presently done in the message store client code, rather than in the Postgres server functions. Now that the implementation is proven in a prototypical sense by having coded in it the client, move the query formulation into the message store server functions so that it's part of the database's responsibilities, rather than the client's.

The Postgres server function should receive an additional parameter named, `correlation`, mirroring the current implementation in the client.

Changes will also be needed in the client, as well as in the consumer.

**Comment by Fire-Dragon-DoL** [comment]
Hey @sbellware can you help me understand the ticket better? Is it referring to supporting [this functionality](https://github.com/eventide-project/consumer-postgres/blob/2eb0b471e600ad8c61dc7a77bcf1e5042d64bdbc/lib/consumer/postgres/controls/condition.rb#L7) directly in message-store-postgres-database (with a function), without having to supply an SQL chunk as a condition?

If yes, I think this code is currently spanning both `consumer-postgres` and `message-store-postgres` (the `message-store-postgres` part is just the support of the condition)

**Comment by sbellware** [comment]
Done
